### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by gilbert**
From the commit message:

- Clean up .query api
- Make .query return solutions instead of matches
- Implement not_ predicate
- Add a to_prolog helper
- Resolved deprecations in test

The query api is a breaking change, but I believe it's worth doing. It allows the caller to read query results much more easily.

Thanks a ton for putting up this gem, looking forward to using it in my next rails project :)

### CODE REVIEW

**Comment by preston** [comment]
@gilbert Would you be interested in maintaining this repository/gem? It's obviously not something I've put time into in recent years.

**Comment by gilbert** [comment]
Yes, I would be honored to be passed the torch :) My rubygems profile is [here](https://rubygems.org/profiles/gilbert).

**Comment by preston** [comment]
@gilbert Looks awesome! Thank you :) Let me know if I need to authorize you for anything additional. You should be an owner now.

**Comment by gilbert** [comment]
Hi @preston, did you mean to add me as an owner on rubygems? I don't have access to push up new versions.

**Comment by preston** [comment]
I forgot to do that. Will look at it now..

Preston

**Pull request merged**
